[package]
name = "beer-necessities"
version = "0.1.0"
authors = ["Nicholas Pun <nicholaspun99@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0-rc.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rocket_cors = "0.4.0"

[[bin]]
name = "main"
path = "src/main.rs"
