[package]
name = "beer-necessities"
version = "0.1.0"
authors = ["Nicholas Pun <nicholaspun99@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"

[[bin]]
name = "main"
path = "src/main.rs"
